Repository nextcloud/bruteforcesettings, pull requests merged in 2024-02, with the labels that each got.

#534 [stable28] chore: composer run cs:fix
  lib/Controller/IPWhitelistController.php
Labels: 4. to release

#541 [stable27] fix(deps): Update CS to match the stable27 PHP versions
  composer.json
  composer.lock
  lib/Controller/IPWhitelistController.php
Labels: 3. to review

#548 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#549 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/documentation.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-sqlite.yml
Labels: dependencies, 3. to review, automated

#550 [stable28] chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-sqlite.yml
Labels: dependencies, 3. to review, automated

#552 [Stable27] Fix(App): Use NC components
  js/bruteforcesettings-main.js
  js/bruteforcesettings-main.js.LICENSE.txt
  js/bruteforcesettings-main.js.map
  package-lock.json
  package.json
  src/App.vue
  src/components/BruteForceItem.vue
  src/main.js
Labels: enhancement

#558 docs(README): Expand and re-organize everything
  README.md
Labels: enhancement
