Repository nextcloud/bruteforcesettings, pull requests merged in 2024-07, with the labels that each got.

#618 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#620 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/documentation.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
Labels: dependencies, 3. to review, automated

#622 Migrate dep5 to toml
  .reuse/dep5
  REUSE.toml
Labels: 3. to review, technical debt
