Repository nextcloud/bruteforcesettings, pull requests merged in 2024-08, with the labels that each got.

#624 Add npm audit action
  .github/workflows/npm-audit-fix.yml
Labels: 4. to release, technical debt

#630 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#631 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#636 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#639 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/documentation.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/reuse.yml
Labels: dependencies, 3. to review, automated
