Repository nextcloud/bruteforcesettings, pull requests merged in 2025-07, with the labels that each got.

#776 ci: update reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#777 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#773 fix: update eslint
  .eslintrc.js
  .gitattributes
  babel.config.js
  eslint.config.mjs
  js/bruteforcesettings-main.js
  js/bruteforcesettings-main.js.map
  package-lock.json
  package.json
  src/App.vue
  src/components/BruteForceItem.vue
  src/main.js
  stylelint.config.js
  webpack.js
Labels: enhancement
